[package]
name = "syndrome-magick"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphicsmagick = "0.2.1"
aws-sdk-s3 = "0.0.23-alpha"
lambda_runtime = "0.4.1"